name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}
  schedule:
    - cron: "0 3 * * 0 "

concurrency:
   group: ci-${{ github.head_ref || github.ref }}
   cancel-in-progress: true

jobs:
  setup:
    name: "Fill Dependency Cache"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
        with:
          # Future installations will run "prepare"
          # and this job doesn't need to
          args: '--ignore-scripts'

  lint:
    name: "Lints"
    needs: ['setup']
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
      - name: "Verify that no manually needed fixes / violations are present"
        run: pnpm lint

  tests:
    name: Default Tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
      - run: pnpm build
      - run: pnpm --filter test-app run test:ember

  floating-deps-tests:
    name: Floating Deps Test
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs:
      - tests
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
        with:
          args: '--no-lockfile'
      - run: pnpm build
      - run: pnpm --filter test-app run test:ember

  try-scenarios:
    name: ${{ matrix.ember-try-scenario }}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs:
      - tests
    strategy:
      fail-fast: false
      matrix:
        ember-try-scenario:
          - ember-3.25
          - ember-lts-3.28
          - ember-lts-4.4
          - ember-lts-4.8
          - ember-lts-4.12
          - ember-lts-5.4
          - ember-lts-5.8
          - ember-release
          - ember-beta
          - ember-canary
          - embroider-safe
          - embroider-optimized
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
      - run: pnpm build
      - run: node_modules/.bin/ember try:one ${{ matrix.ember-try-scenario }} --skip-cleanup
        working-directory: ./test-app
